/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by informer-gen

package v1beta1

import (
	v1 "github.com/r2d4/kube-client/apimachinery/pkg/apis/meta/v1"
	runtime "github.com/r2d4/kube-client/apimachinery/pkg/runtime"
	watch "github.com/r2d4/kube-client/apimachinery/pkg/watch"
	internalinterfaces "github.com/r2d4/kube-client/client-go/informers/internalinterfaces"
	kubernetes "github.com/r2d4/kube-client/client-go/kubernetes"
	v1beta1 "github.com/r2d4/kube-client/client-go/listers/extensions/v1beta1"
	extensions_v1beta1 "github.com/r2d4/kube-client/client-go/pkg/apis/extensions/v1beta1"
	cache "github.com/r2d4/kube-client/client-go/tools/cache"
	time "time"
)

// ThirdPartyResourceInformer provides access to a shared informer and lister for
// ThirdPartyResources.
type ThirdPartyResourceInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1beta1.ThirdPartyResourceLister
}

type thirdPartyResourceInformer struct {
	factory internalinterfaces.SharedInformerFactory
}

func newThirdPartyResourceInformer(client kubernetes.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	sharedIndexInformer := cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				return client.ExtensionsV1beta1().ThirdPartyResources().List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				return client.ExtensionsV1beta1().ThirdPartyResources().Watch(options)
			},
		},
		&extensions_v1beta1.ThirdPartyResource{},
		resyncPeriod,
		cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc},
	)

	return sharedIndexInformer
}

func (f *thirdPartyResourceInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&extensions_v1beta1.ThirdPartyResource{}, newThirdPartyResourceInformer)
}

func (f *thirdPartyResourceInformer) Lister() v1beta1.ThirdPartyResourceLister {
	return v1beta1.NewThirdPartyResourceLister(f.Informer().GetIndexer())
}
